[package]
name = "morph-endo"
version = "0.1.0"
authors = ["Pavel.Sergeev <pavel.sergeev@jetbrains.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"